"""Build the single Splash bundle from ordered app-layer modules; no native code."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
# Ordered business modules and one inline UI tree. Reserved 61-64 files are
# not compiled: they contain obsolete layout experiments, not live widgets.
FILES = [
    '00_storage', '05_subjects', '08_time_protocol',
    '10_expense', '15_period', '20_calendar', '30_flow', '32_recall',
    '35_query_router', '38_modules', '39_relation_repair', '40_coordinator', '50_agent',
    '55_help', '60_ui',
]

# Files whose bodies declare widget trees (not just helpers).
UI_FILES = {'60_ui'}

# Helper/text-style substitutions to apply only to UI tree files so we do
# not accidentally rewrite call-sites in non-UI modules.
STYLE_BUTTON = ('ButtonFlat{',
                'ButtonFlat{draw_bg +: {color: #xf0f3ed color_hover: #xe3eadd color_down: #xd7e3d4 border_size: 0.0 border_radius: 6.0} '
                'draw_text +: {color: ink color_hover: ink color_down: ink} label_walk: Walk{width: Fill height: Fit} '
                'draw_text.text_overflow: Ellipsis draw_text.max_lines: 1 ')
STYLE_TEXTINPUT = ('TextInput{',
                   'TextInput{draw_bg +: {color: #xf4f5f1 color_hover: #xf4f5f1 color_focus: #xffffff color_empty: #xf4f5f1} '
                   'draw_text +: {color: ink color_hover: ink color_focus: ink color_empty: muted color_empty_hover: muted} ')

def build():
    chunks = [(ROOT/'src'/f'{name}.splash').read_text(encoding='utf-8') for name in FILES]
    guide = json.loads((ROOT/'src/user_guide.json').read_text(encoding='utf-8'))
    assert guide and all(section['title'] and section['paragraphs'] for section in guide)
    chunks[FILES.index('55_help')] = 'let help_sections = ' + json.dumps(guide, ensure_ascii=False) + '\n' + chunks[FILES.index('55_help')]
    # Module-boundary checks: only expense-related modules may touch private records.
    for name, source in zip(FILES, chunks):
        if name in ('05_subjects', '08_time_protocol', '15_period', '38_modules', '39_relation_repair', '60_ui', '20_calendar', '30_flow', '32_recall', '35_query_router', '50_agent',
                    '61_app_rail', '62_flow_rail', '63_main_col', '64_workspace'):
            assert 'db.records' not in source and 'c.records' not in source, \
                f'Private expense access in {name}'
    # Apply ButtonFlat/TextInput style overrides only to UI tree files.
    for i, name in enumerate(FILES):
        if name in UI_FILES:
            chunks[i] = chunks[i].replace(STYLE_BUTTON[0], STYLE_BUTTON[1])
            chunks[i] = chunks[i].replace(STYLE_TEXTINPUT[0], STYLE_TEXTINPUT[1])
    (ROOT/'bundle/main.splash').write_text(
        '// Generated by tools/build_event_app.py; edit src/*.splash.\n' + '\n'.join(chunks),
        encoding='utf-8')
    guide_text = '# DailyFlow 使用说明\n\n应用内入口：左下「帮助」，或「全部」中搜索「使用说明」。内容随应用打包，离线可读。\n\n'
    guide_text += '\n\n'.join('## ' + section['title'] + '\n\n' + '\n\n'.join(section['paragraphs']) for section in guide)
    (ROOT/'docs/USER_GUIDE.md').write_text(guide_text + '\n', encoding='utf-8')

if __name__ == '__main__':
    build()
